version: 2.1

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - compile_lint_test

jobs:
  compile_lint_test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}
            - yarn-v1-
      - run:
          name: Install NPM modules
          command: yarn install
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Compile
          command: yarn build
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
